export enum Capability {
  VIEW_ROLES = "VIEW_ROLES",
  REQUEST_ROLE_ACTION = "REQUEST_ROLE_ACTION",
  CREATE_COMMUNITY_ROLE = "CREATE_COMMUNITY_ROLE",
  EDIT_COMMUNITY_ROLE = "EDIT_COMMUNITY_ROLE",
  ASSIGN_APPROVED_ROLE = "ASSIGN_APPROVED_ROLE",
  REMOVE_COMMUNITY_ROLE = "REMOVE_COMMUNITY_ROLE",
  VIEW_ROLE_REQUESTS = "VIEW_ROLE_REQUESTS",
  APPROVE_ROLE_REQUESTS = "APPROVE_ROLE_REQUESTS",
  DENY_ROLE_REQUESTS = "DENY_ROLE_REQUESTS",
  VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",
  USE_AI = "USE_AI",
  MANAGE_TRUSTED_MODERATORS = "MANAGE_TRUSTED_MODERATORS",
  MANAGE_CONFIG = "MANAGE_CONFIG"
}

export type PermissionTier = "OWNER" | "TRUSTED_MODERATOR" | "NONE";

export interface UserCapabilities {
  tier: PermissionTier;
  capabilities: Capability[];
}
